# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'SKUs',
            },
        ),
        migrations.CreateModel(
            name='SKUCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'SKU Categories',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utype', models.CharField(choices=[('KG', 'Kg'), ('GM', 'Gm'), ('NO', 'Nos'), ('L', 'Ltr'), ('ML', 'Ml')], default=None, max_length=2, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='sku',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sku.SKUCategory'),
        ),
    ]
